# Generated by Django 5.1.7 on 2025-06-23 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IotData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_id', models.CharField(max_length=100)),
                ('dev_eui', models.CharField(max_length=100)),
                ('f_port', models.IntegerField(blank=True, null=True)),
                ('data', models.TextField(blank=True, null=True)),
                ('light_lux', models.FloatField(blank=True, null=True)),
                ('ch4_ppm', models.FloatField(blank=True, null=True)),
                ('co2_ppm', models.FloatField(blank=True, null=True)),
                ('barometer', models.FloatField(blank=True, null=True)),
                ('humidity', models.FloatField(blank=True, null=True)),
                ('temperature', models.FloatField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('altitude', models.FloatField(blank=True, null=True)),
                ('rx_info', models.JSONField(blank=True, null=True)),
                ('object_json', models.JSONField(blank=True, null=True)),
                ('timestamp', models.DateTimeField()),
            ],
        ),
    ]
