services:
  backend:
    build:
      context: ./backend
      # default is set to dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
  cronjob:
    build:
      context: ./backend
      dockerfile: cron.Dockerfile
    volumes:
      - ./backend:/app
    restart: unless-stopped    