# Generated by Django 5.1.7 on 2025-06-20 18:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gas',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gas',
            name='gas',
            field=models.CharField(choices=[('CH4', 'Methane'), ('CO', 'Carbon Monoxide'), ('NO2', 'Nitrogen Dioxide'), ('O3', 'Ozone'), ('SO2', 'Sulfur Dioxide')], max_length=4),
        ),
    ]
